### PR TITLE
Fixing scoping issues, adding eslint

### LINKED ISSUE #53: Unused Variables
I found these warnings coming from webpack when minifying crossfilter. This issue is a reminder for me or someone else to take a look.

```
Dropping unused variable oldValues [./~/crossfilter2/src/crossfilter.js:138,0]
Dropping unused variable oldIndex [./~/crossfilter2/src/crossfilter.js:139,0]
Dropping unused variable oldIterablesIndexFilterStatus [./~/crossfilter2/src/crossfilter.js:146,0]
```

I am thinking of adding eslint to catch stuff like this.

### PR DESCRIPTION
**Pull request by MarkHerhold**
This PR fixes lots of scoping and variable declaration issues and adds eslint so we can maintain a standard going forward.

This is a pretty serious change. I've done my best to be careful and to mind the commit history. Discussion is welcome.

Fixes #53

### CODE REVIEW

**Comment by MarkHerhold** [comment]
And of course I mess up CI on the 2nd commit... I'll take a look at this tomorrow.

**Comment by esjewett** [comment]
Thanks! It sounds like this will facilitate breaking up crossfilter.js into a modular form at some point?

Also, just a note: I see you made some changes to quicksort.js. That's appreciated. I think we need a rewrite of quicksort.js at some point as it introduces some optimization problems in Chrome that I think are costing us a lot of performance. I haven't been able to sit down and really understand that function yet.

Will look at this again after the fix.

**Comment by MarkHerhold** [comment]
@esjewett Yes, this PR is meant to help us along the road of splitting up this project into manageable and maintainable pieces. My other PR, #48 what the first step to doing this.

Interesting note about the quicksort. I'll let you hande rewriting that bit! My only thought is that we should see if we can use a performant implementation from somewhere else if possible, and possibly consider splitting it into a different repo under the crossfilter org, complete with its own CI and benchmarking since performance is so important here.

I've fixed the scope issues in quicksort.js wrapping two sections in closures that immediately execute. Another strategy would be to create new variable names like I did in crossfilter.js but in the case of quicksort.js, I think the closures are a cleaner approach.

**Comment by esjewett** [comment]
@MarkHerhold I'd agree about using another implementation of Quicksort. Unfortunately the Crossfilter version has some oddities around casting variables that make this a little difficult, but hopefully once I sit down and figure it out, it will be possible to just use an existing implementation.

Thanks!

**Comment by MarkHerhold** [comment]
@esjewett fixed 👍

**Comment by esjewett** [comment]
I've looked this over and I think it looks good. I will merge but let it sit for a day or so before doing a release based on it so that others can comment if they want, but I don't see any problems and I think these are changes that will help avoid potential problems. Thanks!

**Pull request merged**
