### PR TITLE
Remove data by test function

### PR DESCRIPTION
**Pull request by esjewett**
This addresses issue https://github.com/crossfilter/crossfilter/issues/6, allowing .remove() to take a test function.

### CODE REVIEW

**Comment by esjewett** [comment]
Unfortunately this appears to have issues with using a test function when filters are in place. Looks like it removes both records outside the filter and records outside the test function. Need to investigate a bit.

**Comment by tannerlinsley** [comment]
@esjewett have you investigated this any further?

**Comment by esjewett** [comment]
@tannerlinsley Haven't gotten to it :-(

**Comment by nordfjord** [comment]
Hey guys, just wondering on the progress of this (opens up so many possibilities). I'm thinking about dedicating some time to this PR/issue over the weekend.

@esjewett You said in another thread that this approach was misguided have you figured out why?

**Comment by esjewett** [comment]
@nordfjord No progress since we last updated this. If you can take a look, that would be excellent. You can see what I did in the referenced commits, but I think it would probably be best to start from scratch because those commits were done before the array dimension work. I don't remember why I said it was misguided, unfortunately. When I said in #6 that something was flawed about the approach, I just meant that it was not working but I didn't have a good handle on exactly why. If this was somewhere else, what I may have been getting at was this:

If we are going to support multiple simultaneous filters in any case (that can be switched between), then the remove function would just be updated to remove data in the context of a specific filter. We don't have an issue open for this multiple filter thing, but it has been discussed in issues on the original cross filter repo. In that way of looking at things, this change would be equivalent to creating a new filter `myFilter` based on filterFunction and then calling `crossfilter.remove(myFilter)`, or whatever API we decide on around filters.

So maybe it would make sense to work on that first and this second, but I suspect that the work will be portable, so it won't be wasted to work on this function-based-removal problem directly.

**Comment by nordfjord** [comment]
I think the biggest challenge in this will be that different dimensions will need to remove different values.

Since if a dimension is filtered it only affects the groups of other dimensions which in turn means that a crossfilter wide remove needs to check if each dimension has already filtered an index since if it has we don't want to remove it.

**Comment by esjewett** [comment]
This was fixed in #81. Woohoo!

**Pull request closed without merging**
