### PR TITLE
Fix a overflow in array.js

### LINKED ISSUE #138: crossfilter.groupAll not removing correctly -- depends on number dimensions
I have a crossfilter with a groupAll counting reducer. I have found that when I use a filterFunction on a dimension, I sometimes end up with a discrepancy between crossfilter.groupAll.value() and the crossfilter.allFiltered() size. 

crossfilter.allFiltered always returns the correct items. The groupAll remove function is not called for a certain set of items in the crossfilter, and it reports too many items.

What's weird is that it only seems to happen when I have 32 dimensions on the crossfilter.

So far I've been unable to create a reproducible testcase. It's very reproducible in my code, but I'm not sure how to export that so someone else can inspect it.

I can keep trying to make a test case, but am hoping someone can suggest places to inspect either my code or the crossfilter code to find the problem.

### PR DESCRIPTION
**Pull request by TijmenW**
Fixes #138

It's an one line fix, spend some time to make sure this was the right place to fix it and that there were no overflows somewhere else.

### CODE REVIEW

**Comment by TijmenW** [comment]
This took longer to find than I expected.

**Comment by gordonwoodhull** [comment]
There is some very tricky code in crossfilter! I don't like to say that code is too clever, but sometimes it makes me wonder.

Thanks for the fix! I looked but didn't grok it right away, hope to review more closely soon.

**Comment by thatcort** [comment]
@gordonwoodhull A short doc describing the internal data model would be helpful: how dimensions are stored/updated and what the various bit manipulation shenanigans are meant to do. Otherwise, I'll continue to rely on those smarter than me ;)

**Comment by gordonwoodhull** [comment]
Thanks @thatcort, good idea. When I was learning crossfilter the first time, I wrote up a summary of the internals; I am attaching it. It would be good to clean this up, correct any inaccuracies, and post it to the wiki.
[how-crossfilter-works.txt](https://github.com/crossfilter/crossfilter/files/3383435/how-crossfilter-works.txt)

**Comment by gordonwoodhull** [comment]
@TijmenW, thanks for [pointing out](https://github.com/crossfilter/crossfilter/commit/4750f931b33d58ca998022450ba10e547946417d#r34272123) commit 4750f93, where this bug may have originated.

Since the initialization of `one` was moved verbatim from src/crossfilter.js line 81, I would not be surprised if crossfilter 1.3 has the same bug for dimension number 32.

**Comment by TijmenW** [comment]
Good point, I'm testing that now.

**Comment by TijmenW** [comment]
Ok, it has been broken since the beginning, 39b63536bf559f8a0e88adcbc57b1c0c97b98441.

**Comment by gordonwoodhull** [comment]
Unsigned right-shift by zero bits, wow! Obscure, but I agree that is more clear and elegant.

**Comment by esjewett** [comment]
So is this good to be merged? @gordonwoodhull, I think you have looked at this more than I.

**Comment by gordonwoodhull** [comment]
Yes! The fix is pretty clear once you understand what the problem is.

Thanks @TijmenW for tracking this down!

**Comment by TijmenW** [comment]
I was thinking of maybe adding a comment about what the bit magic actually does when I figured out the rest, but I never really did.

**Comment by esjewett** [comment]
@TijmenW If you'd like to do that, go ahead and then ping me and I'll merge it :) Thank you!

**Comment by TijmenW** [comment]
@esjewett Done.

**Pull request merged**
