### PR TITLE
format project with prettier

### PR DESCRIPTION
**Pull request by hornta**
* Installed prettier and formatted everything. It can be executed with `npm run format`.
* Upgraded eslint and used the recommended settings for detecting syntax errors/bugs.
* eslint now lints every JS file(expect for the UMD files).
* CI lints the source files so to not cause unexpected lint errors in master.
* CI builds the source files so to not cause a failing build in master.
* Split the test and lint script in package.json(this added a new step in the release process).

I tested to build the project and saw no differences in the minified UMD build. I also ran the benchmark and tests after fixing some eslint errors(some warnings about unused variables) and got no unexpected differences with before.

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
I will merge this, but this kind of change is not really super helpful, especially when there are no active maintainers for a project.

In the future, please look for substantive changes you can contribute to open source, rather than “cleanup” tasks. Thank you!

**Comment by gordonwoodhull** [comment]
I started to review this one but it means reading basically every single line of code in the repo.

So I will decline this PR. Please try again when there are active maintainers!

**Comment by gordonwoodhull** [comment]
Again, I'm not against this, just don't have time to review it.

Hoping new maintainers step up.

**Comment by hornta** [comment]
Do you think we can leave this PR open until this repository have an active maintainer so I can keep it up to date with changes in master?

> this kind of change is not really super helpful

I agree with your reason why it isn't helpful because there are no active maintainers but I do believe it's helpful for newcomers to contribute changes.

**Comment by gordonwoodhull** [comment]
Okay, but there really isn’t any difference. 

A pull request is just tracking between two branches. You will need to rebase and (force) push your branch either way.

**Pull request closed without merging**
