### PR TITLE
Lightweight onChange event

### LINKED ISSUE #23: Support for Events or Pub/Sub
After discussing a few awesome ideas with @esjewett, I feel that there is a need to think about some integration points for crossfilter.  One in particular is some way to know externally if the state or data inside a crossfilter has changed.  Adding, removing, and filtering data are the three actions that come to mind.

In our current in-house solution, we are following up all of our calls to these crossfilter methods with a pup-sub like system.  This works great for us, but breaks down when anything outside of our system (plugins, reductio, etc) call these methods for us. 

I think it would be much easier to support some type of pub/sub support to use as an integration point. 

The specific use case that sparked this conversation is my obsession with post-aggregations (think change stats for certain assessors eg. minChange) that can't be performed inside reduce functions, and must be applied after data is done changing (after any significant event in crossfilter).

Thoughts?

### PR DESCRIPTION
**Pull request by tannerlinsley**
Simply pass a callback function into the `.onChange` method of a
crossfilter instance, and that function will be called any time the crossfilter's
data is added to, removed from, or filtered on.

To deregister a callback, simply invoke the function you receive when
registering.

Closes #23

### CODE REVIEW

**Comment by derekperkins** [comment]
:+1: you should rebase your commits so we keep the history clean

**Comment by tannerlinsley** [comment]
Does anyone else have any input on this?  @gordonwoodhull  @esjewett

**Comment by esjewett** [comment]
@tannerlinsley Sorry, I looked originally and forgot to comment. It looks fine to me and is definitely minimal enough for me to be happy with it. My only real concern here is the restructuring of the test data provisioning. I assume the existing tests are unaffected? The tests are a bit byzantine, but I'd just want to verify that they will still fail appropriately after re-factoring.

**Comment by tannerlinsley** [comment]
Yeah I just brought the data reference out of the cross filter method for
use elsewhere. Existing tests were unaffected.

**Comment by esjewett** [comment]
Yup, I think it looks fine.

**Comment by derekperkins** [comment]
For as minimal as the change is and the fact that it doesn't affect any other tests, I think you should go ahead and merge it.

**Comment by esjewett** [comment]
[However you do the thumbs-up thing on Github. I can never remember.]

**Comment by derekperkins** [comment]
I still think you should rebase so that this comes in as a single commit first though.

**Comment by tannerlinsley** [comment]
`:+1:` == :+1:

**Comment by tannerlinsley** [comment]
Holy frick. Those remote-tracking branch update commits are hellish.  They don't show up in rebasing at all. haha

**Comment by derekperkins** [comment]
Perfect. Merging now.

**Comment by gordonwoodhull** [comment]
I think I also reviewed this earlier and forgot to comment. Looks good!

**Pull request merged**
