### PR TITLE
Replace vows test runner with vitest

### PR DESCRIPTION
**Pull request by hornta**
I couldn't get the tests to work in my Windows machine despite trying to update vows to the latest version so I spent some time replacing vows test runner with https://github.com/vitest-dev/vitest

The package-lock version were updated as well to version 2. If it's a problem I can downgrade npm on my side and rerun the installation, otherwise I recommend specyfing the version of npm like so https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines

### CODE REVIEW

**Comment by hornta** [comment]
@gordonwoodhull I couldn't find anyone to request for review so I'm wondering if you have the opportunity to take a quick glance at this when ever you have time

**Comment by gordonwoodhull** [comment]
Hi @hornta, thanks for your effort. 

May I ask your motivation for porting the tests? Are you interested in adding features to crossfilter?

I am not familiar with vite / vitest but I have been away from the JS ecosystem for a couple years. Maybe others could weigh in on whether this is is a good direction for crossfilter.

**Comment by hornta** [comment]
> Hi @hornta, thanks for your effort.
> 
> May I ask your motivation for porting the tests? Are you interested in adding features to crossfilter?

Yes I am and we use it at work as well. I would want to with ease run the tests and for that I ported it.


> I am not familiar with vite / vitest but I have been away from the JS ecosystem for a couple years. Maybe others could weigh in on whether this is is a good direction for crossfilter.
vitest spawned from the vite project but it's not tightly connected with vite. It's a test runner for any javascript code much like Jest is, however Jest has poor support for ESM which is why I choose vite.

**Comment by gordonwoodhull** [comment]
Okay, sounds great - thanks for the rationale. 

I will test and merge later in the week.

Please note that this repo is looking for new maintainers #171, so you might consider volunteering if you anticipate contributing to crossfilter as open source in future years.

**Comment by gordonwoodhull** [comment]
Okay, I've merged this to master. Thanks @hornta!

While I was at it, I updated dependencies and eliminated a security warning. (As usual, it was a security problem in the build system and does not affect the output.)

There are some cosmetic changes to the bundled output as a result of the upgrade to rollup@2.

I usually don't bump the version or make a new release if the only changes are to build infrastructure and tests. Please ping me if a new release is desired.

**Pull request merged**
