### PR TITLE
New crossfilter build

### PR DESCRIPTION
**Pull request by MarkHerhold**
**This is potentially done - please review!**

This PR makes everything a module, enabling better test integration and easier browser builds with browserify. This PR also closes a global variable issue in https://github.com/crossfilter/crossfilter/issues/47

This stemmed from a conversation in PR #43

**TODO:**
- [x] Implement browserify build
- [x] Add the `.version` field from package.json during the build
- [x] Move build, benchmark, and test commands to `package.json`
- [x] Remove existing makefile
- [ ] Add new `crossfilter.js` and `crossfilter.min.js` files?

### CODE REVIEW

**Comment by MarkHerhold** [comment]
There are issues with - we have 2 tests failing and I am having a really difficult time figuring out what is wrong. I'm worried that the errors may be related to variables potentially being scoped too broadly when the tests were written and the modules approach clamped down on some access.

Thoughts/feedback appreciated.

**Comment by esjewett** [comment]
That's probably the issue, or an internal scoping problem. I hope to be able to look at it this weekend.

**Comment by MarkHerhold** [comment]
@esjewett I would really appreciate if you did look at it. I am pretty perplexed myself.

**Comment by esjewett** [comment]
I think the problem is that crossfilter_arrayWiden is undefined in src/crossfilter.js. Needs to be pulled out of the array.js file or otherwise imported?

**Comment by MarkHerhold** [comment]
@esjewett Brilliant. That was it. I had already exported but wasn't referencing it correctly. Thanks!!!

**Comment by MarkHerhold** [comment]
Ping @esjewett @jasondavies @tannerlinsley
This may be complete - please take a look! Comments/questions/complaints welcome.

**Comment by esjewett** [comment]
I did a quick review and it looks good. A few questions before we merge. None of these are show-stoppers in my view, but just things that I'm not sure about:

 1. Does Crossfilter currently work in IE8? If so, then I'd want to have UglifyJS try to preserve this (i.e. remove the --screw-ie8 option).
 2. Currently it looks like running tests requires `npm build; npm test`. It's not a big deal, but in the old world it was enough to do a `make test`, which would do a build if required. Is this something we can do with npm?
 3. The old makefile used different uglifyJS options. Specifically `-c unsafe=true -m`. If it works, I think we should enable these options in the nom-based build as well.

**Comment by MarkHerhold** [comment]
@esjewett 

I'll answer your questions in the same fashion:

1. I was wondering if crossfilter supported IE8 as well. I don't have a way to test it right now and I don't see any statement of support on crossfilter's REDAME. I think that we should not try to support an ancient browser that **Microsoft itself does not even support** any longer.
1. Running tests does not require you to run `npm build`. One of the great benefits of this new build is that the tests run directly against the source instead of the 'built' code so things like stack traces will actually be accurate and bugs should be easier to find.
1. I looked at the `unsafe` flag in browserify's README and wasn't a fan. It seemed like a great way to introduce new errors that are hard to track down. I think we should migrate away from it. https://github.com/substack/node-browserify#usage That being said, we could do a release with it in and a release with it removed...

**Comment by esjewett** [comment]
Ok, fair enough. Can I get a second pair of eyes to look at this quickly? Then I'll merge and try to cut a new release with this build system. (cc @tannerlinsley @gordonwoodhull)

**Comment by MarkHerhold** [comment]
I'm open to thoughts/opinions on IE8 support. However since we don't have browser CI on this repo and no good way for me to test it, I'd be hard pressed to want to include it...

**Comment by esjewett** [comment]
I decided to merge this as I had time right now. If someone else can take a look, I would still appreciate it. I will look at doing a new alpha release shortly.

**Pull request merged**
