### PR TITLE
expand dimension.top() and dimension.bottom() to include offset parameter

### PR DESCRIPTION
**Pull request by nreese**
Added offset parameter to dimension.top() and dimension.bottom() methods. Updated test suite to verify functionality for [issue 33](https://github.com/crossfilter/crossfilter/issues/33)

### CODE REVIEW

**Comment by tannerlinsley** [comment]
Are we good to merge this ? Let make sure we update the wiki/api.

**Comment by esjewett** [comment]
No, not ready yet. The same logic needs to be added to the `if(iterable)` sections of top/bottom.

**Comment by nreese** [comment]
I was not sure what that part did. Can someone explain that causes a
dimension to be iterable?

I can update the pull request with this section filled out as well

**Comment by esjewett** [comment]
It's for array dimensions. They used to be called "iterable". When there is an array dimension, there can be a set of records with no values. They are considered smaller than any other values in the dimension, so are pasted onto the end of the `top` call or at the beginning of the `bottom` call. You just need to implement exactly the same logic while looking through those records, using the same offset and k increments as for the normal records.

**Comment by nreese** [comment]
I have checked the code to handle iterable dimensions. Is there anything
else missing?

Nathan

**Comment by esjewett** [comment]
No, looks good. There is a conflict with #32 though, which I just merged. Would you mind updating your branch to merge against the latest and I'll merge it? Thanks!

**Comment by esjewett** [comment]
Looks like test builds are not running for this pull request. I'm on mobile, but will merge and we'll see what happens to the build...

**Pull request merged**
