### PR TITLE
Fix Typescript types format and improve them

### PR DESCRIPTION
**Pull request by fnberta**
As mentioned in #95, the types I submitted were actually in the wrong format. This PR fixes that and also improves the types a bit. Sorry for the inconvenience, I hope this can make it for 1.4.4!

### CODE REVIEW

**Comment by esjewett** [comment]
Cool - thanks so much. A small bonus of me being overwhelmed and not getting to 1.4.4 the last 2 weekends is that this will get in! :D I'll review soon.

**Comment by esjewett** [comment]
This looks fine to me, and like an improvement. @gordonwoodhull - any comments?

**Comment by gordonwoodhull** [comment]
I'm glad that we're getting proper Typescript support, but I'm not a user of Typescript (yet). 

I think it's safe to iterate on it since it's orthogonal to the rest of the library. 

@fnberta, please continue to submit updates as needed.

**Comment by esjewett** [comment]
This was released in https://github.com/crossfilter/crossfilter/releases/tag/1.4.5

**Pull request merged**
