### PR TITLE
Typescript typings

### PR DESCRIPTION
**Pull request by fnberta**
As suggested in #86, here is a new PR with a typings file that should address the comments made in #86. I've been using this in a project of mine for a while and it worked well so far. Of course there might still be something missing or wrong. Please have a look and let me know what you think.

### CODE REVIEW

**Comment by esjewett** [comment]
This looks reasonable to me. @gordonwoodhull, @fnberta, others - any thoughts?

**Comment by paulsjv** [comment]
This is awesome!  Thanks for the PR and the work.  Is there any way to test the Type Definition?

**Comment by manju-reddys** [comment]
Please merge this to master asap, we need this definition file too (for now I copied it to my project).

@paulsjv I think the existing test-cases should run in es6 module way! though I haven't done it myself!

**Comment by esjewett** [comment]
@manju-reddys Your wish is my command 😄

**Comment by esjewett** [comment]
Targeting 1.4.4 release. Hope to get that out this week...

**Comment by esjewett** [comment]
@fnberta Thank you for the pull request - we really appreciate it.

**Comment by manju-reddys** [comment]
@fnberta thanks a lot, looking forward to 1.4.4 👍

**Comment by fnberta** [comment]
I'm sorry but I just noticed that the format of the type is not correct. As you will include the types inside the package, we don't need the ```declare module 'crossfilter2'``` thing. This is only used when you have a separate typings file outside of the original package. I just copy pasted what I used in my project, hence this oversight. Shall I make a new commit to this branch to fix it?

**Comment by fnberta** [comment]
Also I think I found a slightly nicer way for how some of the types are exported. Please let me know if I should make a new PR or push to this branch.

**Comment by a13531a** [comment]
Hello,
Do you have any updates about availability of **@ types/crossfilter2** npm package?
When you think it will be available for widespread use?
Thanks.

**Comment by esjewett** [comment]
With this it should just be included in the normal npm package, which I think means that there is no need for a @types package. Am I wrong there? Don't really know a ton about the typescript ecosystem, though I do use it on some projects.

**Comment by a13531a** [comment]
Sorry, maybe I didn't express my question clearly. In other words, in this question I meant the availability of the **@ types/crossfilter2** npm package in the "**types**" folder: [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)

**@ types/crossfilter2** - this is the name of this package. The way it is going to be installed is by typing something like this:
```
npm install @types/crossfilter2 --save-dev
```

So, is this package already available somewhere? (I could not find it though)

Thank you.

**Comment by a13531a** [comment]
I meant that [this](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) page says that
> If your package is not written in TypeScript then the second is the prefered approch.

I thought that you would publish the ***.d.ts** file to [@types](https://www.npmjs.com/~types) since crossfilter2 is written in JavaScript.

When do you plan to make the release of crossfilter2@1.4.4?

Thx.

**Comment by paulsjv** [comment]
@a13531a yes that should be added so that other can `npm install` the type definition when 1.4.4 is released.  If the file is not there or is in the incorrect place please open a PR to correct the issues so others can use the `npm install` type definition.

**Comment by fnberta** [comment]
I sense some confusion here. Type definitions can either be included as a .d.ts file in the crossfilter2 package itself or distributed separately as a @types/crossfilter2 package. If the type definitions are rather small and don't depend on other @types packages (which is the case here), I don't see a reason not to include them in the main package. One less package for the user to install.

**Comment by manju-reddys** [comment]
@fnberta is correct. We don't need separate branch for typescript

**Comment by esjewett** [comment]
Releasing `1.4.4` can happen at any time ... that I am able to set aside a few minutes to do it. I've been the bottleneck here, unfortunately. I'll try to do it today.

**Comment by a13531a** [comment]
Thank you everybody! :satisfied:
looking forward to 1.4.4 :sweat_smile::notes:

**Pull request merged**
