### PR TITLE
Limit packaging extraneous files

### PR DESCRIPTION
**Pull request by MarkHerhold**
Currently crossfilter publishes the following files/folders to NPM. This is already pretty good, but we can do better!

```
   84.0 KiB [##########] /src                                                                                                  
   44.0 KiB [#####     ]  crossfilter.js
   12.0 KiB [#         ]  crossfilter.min.js
    4.0 KiB [          ]  package.json
    4.0 KiB [          ]  CONTRIBUTING.md
    4.0 KiB [          ]  README.md
    4.0 KiB [          ]  Makefile
    4.0 KiB [          ]  LICENSE
    4.0 KiB [          ]  component.json
    4.0 KiB [          ]  index.js
    4.0 KiB [          ]  .travis.yml
    4.0 KiB [          ]  .npmignore
```

This PR removes things like `CONTRIBUTING.md` and `.travis.yml`.
`package.json`, the `README`, and the `LICENSE` are automatically retained by NPM.

https://docs.npmjs.com/files/package.json#files

### CODE REVIEW

**Comment by esjewett** [comment]
Thanks for the contribution! Question: Will this actually work? It looks to me like index.js requires ./crossfilter.js, but the files property only includes the src directory. I know this is wacky, but Crossfilter's current build process is wacky. If you want to modernize the build process while you're at it, that would be awesome :-)

**Comment by MarkHerhold** [comment]
@esjewett Hmm good question. It looks like I messed up by not including the crossfilter.js file. Excellent catch. I'll close this and take a look at the build and wrap it all into another PR.

**Comment by esjewett** [comment]
Ok. If you want to just update this pull request to include crossfilter.js and crossfilter.min.js while excluding src/ instead, we could do that as well. Then switch back after updating the build process to be commonJS-compatible. Or just leave it closed and do the build process update. Either approach is appreciated.

**Comment by MarkHerhold** [comment]
@esjewett 
To continue the build conversation here... I did take look at the build and it is pretty poor IMO. I'm looking at making all the modules in `src/` (like `array.js`, `bisect.js`) into actual modules that can be required rather than string concatenating all the files together. This should improve testability and allow use of `'use strict'` if we want. Once the sub-modules are in place, we can easily use browserify to package everything together into a standalone file and test against that directly.

Another plus will be the removal of the Makefile - those commands can be put directly into `package.json`.

**Comment by esjewett** [comment]
@MarkHerhold I think you've hit the nail on the head. Sounds like exactly the right plan to me and would facilitate some future much-needed refactoring of the massive `src/crossfilter.js` file.

**Pull request closed without merging**
