### PR TITLE
Remove extra elements from groupIndex in group removeData()

### PR DESCRIPTION
**Pull request by namannehra**
Closes https://github.com/crossfilter/crossfilter/issues/155

### CODE REVIEW

**Comment by namannehra** [comment]
@gordonwoodhull

**Comment by gordonwoodhull** [comment]
Thanks, yes I saw this. Hope to review soon!

**Comment by namannehra** [comment]
@gordonwoodhull

**Comment by gordonwoodhull** [comment]
I acknowledge this. Sorry I have not had time to review it yet!

**Comment by gordonwoodhull** [comment]
Thanks @namannehra! I added a crashing test based on your report in #155.

The fix looks correct, and fixes both tests.

Released as 1.5.3

**Pull request closed without merging**
