### PR TITLE
Fixes Some tests mutate topics #90

### LINKED ISSUE #90: Some tests mutate topics
Some tests mutate original topic. This may lead to wrong test results if one of test assertions fail before doing  cleanup.

One of such tests &ndash; `remove with predicate`

Consider following example
```
"remove with predicate": {
  topic: function() {
    return crossfilter();
  },
  "test 1": function(data) {
    data.add([{foo: 1}, {foo: 1.1}, {foo: 1.2}]);

    assert.equal(data.size(), 3);
    
    data.remove(function () {
      return true;
    });
  },
  "test 2": function(data) {
    data.add([{foo: 1}, {foo: 1.1}, {foo: 1.2}]);

    assert.equal(data.size(), 3);

    data.remove(function () {
      return true;
    });
  },
  "test 3": function() {
    data.add([{foo: 1}, {foo: 1.1}, {foo: 1.2}]);

    assert.equal(1, 2);

    data.remove(function () {
      return true;
    });
  }
}
```

Hash iteration is not specified by ECMAScript and is implementation dependent. So above test may executed test 1, test 2, test 3 in any order:

Expected
```
test 1 passed
test 2 passed
test 3 failed
```

Not Expected
```
test 1 passed
test 3 failed
test 2 failed
```

Not Expected
```
test 3 failed
test 1 failed
test 2 failed
```

### PR DESCRIPTION
**Pull request by hornta**
* Fixes #90
* Added spacing between each test and describe for increased readability

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
Thanks @hornta, rebased and merged as 0c35c84

**Comment by gordonwoodhull** [comment]
Very clean and clear solution to the problem, btw. Appreciate the formatting too!

**Comment by hornta** [comment]
> Very clean and clear solution to the problem, btw. Appreciate the formatting too!

Thanks. By the way, what's your stance on formatting the source files with https://prettier.io/? I think it can make contributing easier so you don't have to think about formatting rules and the default ones are really good. I use it everyday and it's built in into my IDE but I've got to disable it so to not cause too many diffs, but it's a pain when your code is not formatted anymore :-)

**Comment by gordonwoodhull** [comment]
We could do that.

Again, I'm retiring from the project at the end of the year, so it's really up to the new maintainers (once they step forward) how they want to manage such problems.

**Comment by hornta** [comment]
Great. I'm afraid that I know too little about the inner workings of crossfilter, otherwise I think I could help out with stuff around.

**Pull request closed without merging**
