### PR TITLE
dimension.accessor

### PR DESCRIPTION
**Pull request by esjewett**
Adds dimension.accessor that allows access to the accessor function used to define the dimension.

### CODE REVIEW

**Comment by tannerlinsley** [comment]
Looks great!

**Comment by esjewett** [comment]
Documented at https://github.com/crossfilter/crossfilter/wiki/API-Reference#wiki-dimension_accessor

**Comment by OzgunBas94** [comment]
@esjewett how can i add information from my data in my tooltip

im using the crossfilter and these charts: dc.rowChart and dc.barChart.
i tried it with the d.value and d.key this works but can i save there more then these two information?

**Comment by gordonwoodhull** [comment]
Hi @OzgunBas94, it's not a great practice to ask random questions on random issues and pull requests. This sounds like a support question, which really belongs on stackoverflow.com with the dc.js tag, or on the [dc.js users group](https://groups.google.com/forum/?fromgroups#!forum/dc-js-user-group) - both @esjewett and I are pretty active in those places.

**Comment by OzgunBas94** [comment]
I'm sorry i'm just new here :(

**Pull request merged**
