### PR TITLE
.all() method

### PR DESCRIPTION
**Pull request by tannerlinsley**
.all method for dumping all rows currently in a cross filter

### CODE REVIEW

**Comment by esjewett** [comment]
Would it be possible to add a basic test case for this?

**Comment by esjewett** [comment]
Looks good. Tests pass for me.

**Comment by gordonwoodhull** [comment]
LGTM too, tests pass.

**Comment by tannerlinsley** [comment]
Added documentation as well to the wiki https://github.com/crossfilter/crossfilter/wiki/API-Reference#crossfilter_all

**Pull request merged**
