### PR TITLE
Dimensions using Arrays

### PR DESCRIPTION
**Pull request by tannerlinsley**
Allows passing an optional boolean as the second parameter to the `dimension` method, instructing cross filter to create a special Iterable dimension.

Refer to docs for usage and examples

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
I'm still not quite grasping what this feature is. Where can I find the documentation?

**Comment by derekperkins** [comment]
@gordonwoodhull It's basically native support for nested arrays.

**Comment by gordonwoodhull** [comment]
As keys or as values?

**Comment by esjewett** [comment]
@gordonwoodhull As group keys. It covers a lot of groupAll scenarios. Pretty much wherever a record should get aggregated to more than one group, we'd move to using this. It replicates Reductio's groupAll functionality but is a lot faster (and will probably get faster still).

**Comment by esjewett** [comment]
Need to add docs of course - I can help with that. Also I want to test the performance impact on normal dimensions.

**Comment by tannerlinsley** [comment]
@gordonwoodhull I've written up some basic docs here: https://github.com/crossfilter/crossfilter/wiki/API-Reference#dimension_with_arrays

**Comment by tannerlinsley** [comment]
Also, if anyone is a wizard at squashing commits, this one could use some :facepunch:

**Comment by r4j4h** [comment]
I am excited for this feature! I am pretty good at squashing but might not be able to get to it till tonight.

**Comment by tannerlinsley** [comment]
Still working out a few micro bugs.  All tests are passing, but there are a few edge cases that there are no tests written for yet. 

@esjewett and I both have pretty sophisticated apps that use crossfilter in the wild, so we're going to try and pinpoint those edge cases and get them taken care of.

While we're doing that, it would be great if anyone wanted to proofread the doc changes I just made on the wiki.

**Comment by esjewett** [comment]
Here's a codepen example: http://codepen.io/esjewett/pen/JXPBqj

If you filter on the product ID row chart, you'll see that we seem to have some bugs. It looks to me like rows are not getting added/removed correctly on filtering.

**Comment by esjewett** [comment]
Interestingly, in @tannerlinsley's app, this didn't seem to happen. So maybe the filter is getting applied differently. Not sure.

**Comment by esjewett** [comment]
That codepen now works. @gordonwoodhull, maybe will help answer your question: http://codepen.io/esjewett/pen/JXPBqj

**Comment by gordonwoodhull** [comment]
I think I get it. It's this old frequently asked question, right?

http://stackoverflow.com/questions/17524627/is-there-a-way-to-tell-crossfilter-to-treat-elements-of-array-as-separate-record

**Comment by esjewett** [comment]
@gordonwoodhull That's it. Also useful for moving averages and such. The issue that Tanner ran into is that there is a performance bottleneck when implemented using groupAll that it doesn't seem possible to get around. Thought implementing directly in Crossfilter would be better for performance and for usability since it is a common use-case.

**Comment by tannerlinsley** [comment]
So what else needs to happen here before we merge ftw? :tada:

**Comment by r4j4h** [comment]
#28 was just updated to include all current commits as of my posting this. :balloon:

**Comment by esjewett** [comment]
@r4j4h Thanks for that! Question because I've never tried this: Is there any way to rename the commit to reflect the feature being added?

@tannerlinsley How are we looking on removing data? I think we need to review/test that before cutting a release. I'd be alright merging to master with @r4j4h's squashed commit.

**Comment by tannerlinsley** [comment]
Yeah, I'm good then merging to master.  As long as we write that last test for removing data before we do a release, yes.

**Comment by r4j4h** [comment]
@esjewett Yep I can rename the commit to whatever you would like.

**Comment by tannerlinsley** [comment]
Merged via #28.  We'll get `remove` tests in there before we cut a release

**Pull request closed without merging**
