### PR TITLE
default export

### PR DESCRIPTION
**Pull request by MingboPeng**

### CODE REVIEW

**Comment by esjewett** [comment]
This makes sense. Sorry I didn't see it before now. I'm really behind and was supposed to cut a Crossfilter release a few weeks ago but haven't even gotten to that yet :D.

Will it break any existing imports?

**Comment by MingboPeng** [comment]
the existing imports will still work. I don't think this will break any current imports.

**Comment by fnberta** [comment]
Considering the structure of how crossfilter exports stuff, typing it as default export is actually wrong. Hence I would refrain from doing that. As a consumer, you can get the same "import experience" by using ```esModuleInterop: true``` in your tsconfig.json.

**Comment by esjewett** [comment]
@MingboPeng and @fnberta Did we ever come to an agreement on how to do this? I left this alone because it seemed there was some disagreement. If we can clarify and get this incorporated (or not), that would be good. Thanks!

**Comment by fnberta** [comment]
I still don't think we should do that. I actually think it will break things as it will look for a default property in crossfilter which is not available. It might work though if there is some magic somewhere in the build chain that detects that default is actually not available but the top level export is callable and uses that instead).

Exactly for these kind of situations, TS introduced the ```esModuleInterop: true``` flag. https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html

**Comment by MingboPeng** [comment]
@fnberta  thanks for sharing more details that I wasn't aware of. I am closing this pull request. Thanks again!

**Comment by esjewett** [comment]
Thanks @fnberta and @MingboPeng for resolving this!

**Pull request closed without merging**
